version: '2.0'
x-services:
  loghost:
  dns:
  pki:
  mail:
  krb:
  irc:
  finger:
  whois:
  news:
services:
  server:
    container_name: server
    hostname: server.zsft.ru
    image: zartsoft/fedora:server
    build:
      context: .
      target: server
    command: [ "/usr/lib/systemd/systemd", "quiet" ]
    tty: true
    #privileged: true
    network_mode: bridge
    logging: { driver: local }
