services:
  server:
    &common
    # configure corporate proxy for build process
    build:
      args:
        - http_proxy=http://10.8.229.82:3128
        - https_proxy=http://10.8.229.82:3128
        - ftp_proxy=http://10.8.229.82:3128
        - no_proxy=localhost,.gazprom-neft.local,127.,10.,192.168.
    # systemd support for non-rh docker
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#  loghost: *common
