version: '3.4'
services:
  loghost:
    hostname: loghost
    domainname: $DOMAIN
    image: $IMAGE:loghost
    container_name: loghost
    build:
      target: loghost
  server:
    hostname: server
    domainname: $DOMAIN
    image: $IMAGE:server
    container_name: server
    build:
      target: server
    depends_on:
      - loghost
networks:
  default:
    name: $DOMAIN
