version: '2.4'
services:
  server:
    container_name: server
    hostname: server.zsft.ru
    image: zartsoft/fedora:server
    build:
      context: .
      target: server
    tty: true
    privileged: true
    userns_mode: "host"
