version: '3.4'
x-services:
  loghost:
  dns:
  pki:
  mail:
  krb:
  irc:
  finger:
  whois:
  news:
services:
  loghost:
    hostname: loghost.zsft.ru
    image: zartsoft/fedora:loghost
    build:
      context: .
      target: loghost
    command: [ "/usr/lib/systemd/systemd", "quiet"]
    tty: true
  krb5:
    hostname: krb.zsft.ru
    image: zartsoft/fedora:krb5
    build:
      context: .
      target: krb5
      args:
        KRB5_REALM: ZSFT.RU
    command: [ "/usr/lib/systemd/systemd", "quiet"]
    depends_on:
      - loghost
    tty: true
  server:
    hostname: server.zsft.ru
    image: zartsoft/fedora:server
    build:
      context: .
      target: server
    command: [ "/usr/lib/systemd/systemd", "quiet"]
    depends_on:
      - loghost
    #privileged: true
    #network_mode: bridge
